### ISSUE TITLE
Unable to utilize demo, 'default(...) is not a function'

### ISSUE THREAD

**Issue by sirramongabriel** [Sparticuz/pdffiller-stream#14]
**Expected Behavior**
  

- For the pdf firstName & lastName fields to be filled in with text, as the code I used is based off the demo

**Current Behavior**
 

- ` "TypeError: _sparticuz_pdffiller__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function"`

**Possible Solution**

-   ?

**Steps to Reproduce**
  

- `npm install --save @sparticuz/pdffiller" (this is -v3.0.1)`

- `const sourcePDF = "test/test.pdf";`

-  `const data = {
          "firstName" : "John",
          "lastName" : "Doe",
      };`

-   `fillForm(sourcePDF, data)
          .then((outputStream) => {
              // use the outputStream here;
              // will be instance of stream.Readable
              console.log('output - '+JSON.stringify(outputStream))
          }).catch((err) => {
              console.log(err);
          });`

**Context** (Environment)

- Ubuntu 18.04 LTS

- Node v12.18.3

- Npm v6.14.6

- Vue-cli v3.6.3

**Detailed Description**
  

- I'm having trouble getting the demo code to work with my pdf 

**Possible Implementation**

I was facing this issue [#85](https://github.com/pdffillerjs/pdffiller/issues/85) from pdffillerjs/pdffiller & found your library via search

**Comment by Sparticuz** [comment]
Sorry, totally missed this issue. I'm not very familiar with Webpack. However, that error makes it seem it's having trouble importing the default export. You may need to import the module a different way? 
Try `const fillForm = require("@sparticuz/pdffiller").default;`

**Comment by sirramongabriel** [comment]
Thank you. I'm not seeing this issue any longer. I'll post a separate issue for the new error being shown in the near future.
